spring:
  datasource:
    name: test
    url: jdbc:mysql://172.17.105.39:3306/blog_admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
      database: 0
      host: 172.17.105.39
      pool:
        max-active: 20
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: hzqing.com.blogadmin.entity
server:
  port: 8899
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
blog:
  images:
    path: /home/hzq/hblog/
  access:
    token: 'access-token'
admin:
  jwt:
    secret: 'hzqing'
    expiration: 6000
